blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=140)
    text = models.TextField()
    published = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.shortcuts import render
from .models import Post


# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'blog/index.html', context)

def detail(request, pk):
    post = Post.objects.get(pk=pk)
    context = {'post': post}
    return render(request, 'blog/detail.html', context)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
     integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Django Blog Project</title>
</head>
<body>

{% block content %}

{% endblock content %}

</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="container-sm">
    <h3>{{ post.title }}</h3>
    <p class="text-muted small">{{ post.published }}</p>
    <p class="word-wrap" style="width: 50rem;"> {{ post.text }}</p>
    <br></br>
    <a href="{% url 'blog:index' %}" class="btn btn-primary">Go Back</a>
</div>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 class="display-1">Django Blog</h1>
    <br></br>
    {% for post in posts %}
    <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text text-muted small">{{ post.published }}</p>
            <p class="card-text">{{ post.text | truncatechars:50 }}</p>
            <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Read More</a>
        </div>
    </div>
    {% endfor %}
{% endblock content %}
</html>